export const TARGET_OWNER = "j3w1";
export const TARGET_REPOSITORY = "j3w1.github.io";
export const TARGET_BRANCH = "main";
export const TARGET_REPOSITORY_WITH_OWNER = `${TARGET_OWNER}/${TARGET_REPOSITORY}`;

export const J3W1CTL_API_PROTOCOL = 1;
export const SESSION_SCHEMA_VERSION = 1;
export const SESSION_TTL_SECONDS = 60 * 60;
export const UPLOAD_BATCH_SCHEMA_VERSION = 1;
export const UPLOAD_BATCH_TTL_SECONDS = 30 * 60;
export const STAGING_PREFIX = "staging/j3w1ctl/";

export const PRODUCTION_SECRET_NAMES = Object.freeze([
  "CMS_SESSION_SECRET",
  "GITHUB_APP_ID",
  "GITHUB_CLIENT_ID",
  "GITHUB_CLIENT_SECRET",
  "GITHUB_PRIVATE_KEY_BASE64",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN",
  "BLOB_READ_WRITE_TOKEN",
  "CRON_SECRET",
]);

export const PRODUCTION_REQUIRED_NAMES = Object.freeze([
  "CMS_SITE_ORIGIN",
  "CMS_ALLOWED_GITHUB_LOGIN",
  "CMS_ALLOWED_GITHUB_USER_ID",
  "CMS_SESSION_SECRET",
  "GITHUB_APP_ID",
  "GITHUB_CLIENT_ID",
  "GITHUB_CLIENT_SECRET",
  "GITHUB_PRIVATE_KEY_BASE64",
  "GITHUB_CALLBACK_URL",
  "GITHUB_API_VERSION",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN",
  "BLOB_READ_WRITE_TOKEN",
  "CRON_SECRET",
]);
